### ISSUE TITLE
Initialising GIT repository failed error

### ISSUE THREAD

**Issue by valentinoPereira** [sebastiande/insomnia-plugin-git-sync#2]
I have created a git repository on remote and cloned it on my local machine. 

I open my insomnia request collection and set the url to that repository URL. When I try to use the feature "Pull from GIT" or "Push to GIT", I get the following error
<img width="389" alt="Screenshot 2022-01-14 at 4 29 10 PM" src="https://user-images.githubusercontent.com/21219324/149505177-70fad75f-e9c2-4993-8da3-a887910830e2.png">

I do what the error tells me to do, but its of no use as this error keeps coming when I try to pull or push again.

FYI: I am using GitHub repository. 

Is there any workaround or fix for this?

**Comment by sebastiande** [comment]
@valentinoPereira is your repository empty? Does the local project already contains requests etc.?

Have you already tried to also delete the local Insomnia project and create a new one?

**Comment by andrew-weber** [comment]
You need to make sure git is installed.
Looks like you're on mac.

```
brew install git
```

after that you may have a few more errors, but you can easily solve them if you open up the developers console.

**Comment by sebastiande** [comment]
I added a check if git is installed so there is at least an alert if it is missing.

**Comment by kolindes** [comment]
The same error is still appearing when i click on button "Pull from Git".

![image](https://user-images.githubusercontent.com/55790812/183855867-1589f68b-6c0b-42a7-a9d8-f2e50152fe25.png)

Guess the problem is with missing authorization credentials. When i installed plugin from my windows 10 home PC and ran it for a first time the plugin initialized login window and everything gone OK. 

And now i tried to do same from my windows 11 Laptop and login window wont initialize.

![image](https://user-images.githubusercontent.com/55790812/183856988-6cf2e1e2-2973-4825-a591-84395685ec2d.png)

Is there any solutions for this case?

**Comment by bkolo** [comment]
i hve the same exact issue as well
